<hr/>
<div class="row">
  <div class="col-sm-2 col-sm-offset-1 col-xs-6">
    <p><strong><?=$this->transEsc('Search Options')?></strong></p>
    <ul>
      <li><a href="<?=$this->url('search-history')?>"><?=$this->transEsc('Search History')?></a></li>
      <li><a href="<?=$this->url('search-advanced')?>"><?=$this->transEsc('Advanced Search')?></a></li>
    </ul>
  </div>
  <div class="col-sm-2 col-xs-6">
    <p><strong><?=$this->transEsc('Find More')?></strong></p>
    <ul>
      <li><a href="<?=$this->url('browse-home')?>"><?=$this->transEsc('Browse the Catalog')?></a></li>
      <li><a href="<?=$this->url('alphabrowse-home')?>"><?=$this->transEsc('Browse Alphabetically')?></a></li>
      <li><a href="<?=$this->url('search-newitem')?>"><?=$this->transEsc('New Items')?></a></li>
    </ul>
  </div>
  <div class="col-sm-2 col-xs-6">
    <p><strong><?=$this->transEsc('Need Help?')?></strong></p>
    <ul>
      <li><a href="<?=$this->translate('footer.howtorequest.href')?>"><?=$this->transEsc('footer.howtorequest')?></a></li>
      <li><a href="<?=$this->url('help-home')?>?topic=search" class="help-link" title="<?=$this->transEsc('Search Tips')?>"><?=$this->transEsc('Search Tips')?></a></li>
      <li><a href="<?=$this->url('iish-about')?>" class="iish-about-link"><?=$this->transEsc('About')?></a></li>
      <li><a href="<?=$this->url('iish-databases')?>" class="iish-databases-link"><?=$this->transEsc('Databases')?></a></li>
      <li><a href="<?=$this->translate('footer.href.ask')?>"><?=$this->transEsc('Ask a Librarian')?></a></li>
      <li><a href="<?=$this->translate('footer.href.faq')?>"><?=$this->transEsc('FAQs')?></a></li>
    </ul>
  </div>
  <div class="col-sm-2 col-xs-6">
    <p><strong><?=$this->transEsc('more.information')?></strong></p>
    <ul>
      <li><a href="<?=$this->translate('more.information.iish')?>">IISG</a></li>
      <li><a href="<?=$this->translate('more.information.neha')?>">NEHA</a></li>
      <li><a href="<?=$this->translate('more.information.persmuseum')?>">Persmuseum</a></li>
      <li><a href="<?=$this->translate('more.information.termsandconditions.href')?>"><?=$this->translate('more.information.termsandconditions')?></a></li>
    </ul>
  </div>
  <div class="col-sm-2 col-xs-6">
    <p><strong><?=$this->transEsc('see.also')?></strong></p>
    <ul>
      <li><a href="<?=$this->translate('see.shp.href')?>" title="<?=$this->translate('see.shp.title')?>"><?=$this->transEsc('see.shp.text')?></a></li>
      <li><a href="<?=$this->translate('see.apex.href')?>" title="<?=$this->translate('see.apex.title')?>"><?=$this->transEsc('see.apex.text')?></a></li>
      <li><a href="<?=$this->translate('see.europeana.href')?>" title="<?=$this->translate('see.europeana.title')?>"><?=$this->transEsc('see.europeana.text')?></a></li>
      <li><a href="<?=$this->translate('see.worldcat.href')?>" title="<?=$this->translate('see.worldcat.title')?>"><?=$this->transEsc('see.worldcat.text')?></a></li>
    </ul>
  </div>
</div>
