<?
  // Set up standard record scripts:
  $this->headScript()->appendFile("record.js");
  $this->headScript()->appendFile("check_save_statuses.js");
  // Activate Syndetics Plus if necessary:
  if ($this->syndeticsPlus()->isActive()) {
    echo $this->headScript()->appendFile($this->syndeticsPlus()->getScript());
  }

  // Add RDF header link if applicable:
  if ($this->export()->recordSupportsFormat($this->driver, 'RDF')) {
    $this->headLink()->appendAlternate($this->recordLink()->getActionUrl($this->driver, 'RDF'), 'application/rdf+xml', 'RDF Representation');
  }

  // Set up breadcrumbs:
  $options = $this->searchOptions($this->searchClassId);
  $this->layout()->breadcrumbs =
    '<li><a href="' . $this->url($options->getSearchAction()) . '">' . $this->transEsc('New Search') . '</a></li> ' .
    '<li>' . $this->getLastSearchLink($this->transEsc('Search Results'), '', '</li> ') .
    '<li class="active">' . $this->recordLink()->getBreadcrumb($this->driver) . '</li> ';
  $this->layout()->title = $this->driver->getShortTitle();

  $isEAD = $this->driver instanceof \IISH\RecordDriver\SolrEad;
?>

<div class="row">
  <? if ($isEAD): ?>
    <div id="navigation-container" class="col-sm-2 hidden-print">
      <div id="navigation">
        <div class="loading text-center">
          <img src="<?=$this->imageLink('ajax_spinner.gif')?>" alt="Loading" />
        </div>
      </div>
    </div>
  <? endif; ?>

  <div class="<?=$isEAD ? 'col-sm-7' : $this->layoutClass('mainbody')?>">
    <div class="record-well well well-sm hidden-print">
      <?=$this->record($this->driver)->getToolbar()?>

      <? if (isset($this->scrollData) && ($this->scrollData['previousRecord'] || $this->scrollData['nextRecord'])): ?>
        <ul class="pager">
          <? if ($this->scrollData['previousRecord']): ?>
            <li>
              <a href="<?=$this->recordLink()->getUrl($this->scrollData['previousRecord'])?>" title="<?=$this->transEsc('Previous Search Result')?>">&laquo; <?=$this->transEsc('Prev')?></a>
            </li>
          <? else: ?>
            <li class="disabled"><a href="#">&laquo; <?=$this->transEsc('Prev')?></a></li>
          <? endif; ?>
          #<?=$this->escapeHtml($this->scrollData['currentPosition']) . ' ' . $this->transEsc('of') . ' ' . number_format($this->escapeHtml($this->scrollData['resultTotal'])) . ' ' . $this->transEsc('results') ?>
          <? if ($this->scrollData['nextRecord']): ?>
            <li>
              <a href="<?=$this->recordLink()->getUrl($this->scrollData['nextRecord'])?>" title="<?=$this->transEsc('Next Search Result')?>"><?=$this->transEsc('Next')?> &raquo;</a>
            </li>
          <? else: ?>
            <li class="disabled"><a href="#"><?=$this->transEsc('Next')?> &raquo;</a></li>
          <? endif; ?>
        </ul>
      <? endif; ?>
    </div>

    <div class="record recordId source<?=$this->escapeHtmlAttr($this->driver->getResourceSource())?>" id="record">
      <input type="hidden" value="<?=$this->escapeHtmlAttr($this->driver->getUniqueId())?>" class="hiddenId" id="record_id" />
      <input type="hidden" value="<?=$this->escapeHtmlAttr($this->driver->getResourceSource()) ?>" class="hiddenSource" />
      <?=$this->flashmessages()?>
      <?=$this->record($this->driver)->getCoreMetadata()?>
    </div>

    <? if (count($this->tabs) > 0): ?>
      <a name="tabnav"></a>
      <ul class="recordTabs nav nav-tabs">
        <? foreach ($this->tabs as $tab => $obj): ?>
        <? // add current tab to breadcrumbs if applicable:
          $desc = $obj->getDescription();
          $isCurrent = (strtolower($this->activeTab) == strtolower($tab));
          if ($isCurrent) {
            $this->layout()->breadcrumbs .= '<li class="active">' . $this->transEsc($desc) . '</li>';
            $activeTabObj = $obj;
          }
        ?>
        <? $hasNavigation = (($obj instanceof \IISH\RecordTab\ArchiveBase) && $obj->hasNavigation()); ?>
        <? $navigationLink = $this->url('navigation', array('id' => $this->driver->getUniqueID(), 'tab' => $tab)); ?>
        <li<?=$isCurrent ? ' class="active"' : ''?>>
          <a id="<?=strtolower($tab) ?>" href="<?=$this->recordLink()->getTabUrl($this->driver, $tab)?>#tabnav"
            <? if ($hasNavigation): ?>data-navigation="<?=$navigationLink?>"<? endif; ?>><?=$this->transEsc($desc)?></a>
        </li>
        <? endforeach; ?>

        <li class="dropdown responsive-dropdown" style="display:none;">
          <a class="btn dropdown-toggle" data-toggle="dropdown" href="#">
            <span class="caret"></span>
          </a>
          <ul class="dropdown-menu"></ul>
        </li>
      </ul>
    <? endif; ?>

    <div class="tab-content" id="record-tabs">
      <div class="tab-pane active" id="<?=$this->activeTab ?>-tab">
        <?=isset($activeTabObj) ? $this->record($this->driver)->getTab($activeTabObj) : '' ?>
      </div>
    </div>

    <span class="Z3988" title="<?=$this->escapeHtmlAttr($this->driver->getOpenURL())?>"></span>
  </div>

  <div class="<?=$this->layoutClass('sidebar')?>">
    <? foreach ($this->related()->getList($this->driver) as $current): ?>
      <?=$this->related()->render($current)?>
    <? endforeach; ?>
  </div>
</div>
