<?
    // Set up page title:
    $this->headTitle($this->translate('New Item Search'));

    // Set up breadcrumbs:
    $this->layout()->breadcrumbs = '<li class="active">' . $this->transEsc('New Items') . '</li>';
?>
<div class="<?=$this->layoutClass('mainbody')?>">
  <h2><?=$this->transEsc('Find New Items')?></h2>
  <form method="get" action="" class="form-horizontal">

    <div class="row">
      <div class="form-group col-sm-6">
        <label class="col-sm-4 control-label"><?=$this->transEsc('Range')?>:</label>
        <div class="col-sm-8">
          <? foreach ($this->ranges as $key => $range): ?>
            <div class="radio">
              <label>
                <input type="radio" name="range" id="newitem_range_<?=$this->escapeHtmlAttr($key)?>" value="<?=$this->escapeHtmlAttr($range)?>"<?= ($key == 0) ? ' checked="checked"' : ''?>/>
                <?=($range == 1) ? $this->transEsc('Yesterday') : $this->transEsc('Past') . ' ' . $this->escapeHtml($range) . ' ' . $this->transEsc('Days')?>
              </label>
            </div>
          <? endforeach; ?>
        </div>
      </div>

      <div class="form-group col-sm-4">
        <select class="form-control" id="limit_format" name="filter[]" size="8">
        <?
        // Sort the current facet list alphabetically; we'll use this data
        // along with the foreach below to display facet options in the
        // correct order.
        $sorted = array();
        foreach ($this->formats['list'] as $i => $value) {
          if (!empty($value['displayText'])) {
            $sorted[$i] = $value['displayText'];
          }
        }
        natcasesort($sorted);
        ?>
        <? foreach ($sorted as $i => $display): ?>
          <? $value = $this->formats['list'][$i]; ?>
          <option value="<?=$this->escapeHtmlAttr(($value['operator'] == 'OR' ? '~' : '') . 'format:"' . $value['value'] . '"')?>"<?=(isset($value['selected']) && $value['selected'])?' selected="selected"':''?>><?=$this->escapeHtml($display)?></option>
        <? endforeach; ?>
      </select>
    </div>

    <? if (is_array($this->fundList) && !empty($this->fundList)): ?>
      <div class="form-group">
        <label class="col-sm-3 control-label" for="newitem_department"><?=$this->transEsc('Department')?>:</label>
        <div class="col-sm-9">
          <select id="newitem_department" name="department" size="10" class="form-control">
          <? foreach ($this->fundList as $fundId => $fund): ?>
            <option value="<?=$this->escapeHtmlAttr($fundId)?>"><?=$this->transEsc($fund)?></option>
          <? endforeach; ?>
          </select>
        </div>
      </div>
    <? endif; ?>

    <div class="form-group">
      <div class="col-sm-11 col-sm-offset-1">
        <input class="btn btn-primary" type="submit" name="submit" value="<?=$this->transEsc('Find')?>"/>
      </div>
    </div>
  </form>
</div>
<div class="clear"></div>