<? $this->headTitle($this->translate('Holdings') . ': ' . $this->driver->getBreadcrumb()); ?>

<? $holdings = $this->driver->getHoldings(); if (!empty($holdings)): ?>
  <h4><?=$this->transEsc('Holding')?></h4>

  <div id="holdings">
    <? foreach ($holdings as $counter => $holding): ?>
      <div class="holding">
        <div class="info">
          <div class="callnumber">
            <?=$this->escapeHtml($holding['c'])?>
          </div>

          <? if (isset($holding['p'])): ?>
            <div class="digital loading hidden-print"
                 data-record="<?=$this->escapeHtml($this->driver->getUniqueId())?>"
                 data-item="<?=$this->escapeHtml($holding['p'])?>">
              <i class="fa fa-spinner fa-spin"></i>
            </div>
          <? endif; ?>

          <? $formats = $this->driver->getFormats(); $format = strtolower($formats[0]); ?>
          <? if (($format === 'books and brochures') || ($format === 'serials')): ?>
            <div class="state hidden-print"
                 data-label="<?=$this->escapeHtmlAttr($this->truncate(preg_replace('/[\'"]/', '`',
                   $this->driver->getShortTitle()), 40))?> - <?=$this->escapeHtmlAttr($holding['j'])?>"
                 data-pid="<?=$this->escapeHtmlAttr($this->driver->getIsShownAt())?>"
                 data-signature="<?=$this->escapeHtmlAttr($holding['j'])?>">
            </div>
          <? endif; ?>
        </div>

        <? if (isset($holding['note'])): ?>
          <div class="note">
            <?=$this->escapeHtml($holding['note'])?>
          </div>
        <? endif; ?>
      </div>
    <? endforeach; ?>
  </div>
<? endif; ?>

<? if ($this->usertags()->getMode() !== 'disabled'): ?>
  <? $tagList = $this->driver->getTags(); ?>
  <div class="tags">
    <h4><?=$this->transEsc('Tags')?></h4>

    <div class="row">
      <div class="col-sm-6">
        <span class="pull-right hidden-print">
          <i class="fa fa-plus"></i> <a id="tagRecord" class="modal-link" href="<?=$this->recordLink()->getActionUrl($this->driver, 'AddTag')?>" title="<?=$this->transEsc('Add Tag')?>"><?=$this->transEsc('Add Tag')?></a>
        </span>

        <div id="tagList">
          <? if (count($tagList) > 0): ?>
            <? $i = 0; foreach ($tagList as $tag): ?><?=($i++ == 0)?'':', '?><a href="<?=$this->url('tag-home')?>?lookfor=<?=urlencode($tag->tag)?>"><?=$this->escapeHtml($tag->tag)?></a> (<?=$this->escapeHtml($tag->cnt)?>)<? endforeach; ?>
          <? else: ?>
            <?=$this->transEsc('No Tags')?>, <?=$this->transEsc('Be the first to tag this record')?>!
          <? endif; ?>
        </div>
      </div>
    </div>
  </div>
<? endif; ?>

<?
$isShownAt = $this->driver->getIsShownAt();
$imageURL = $this->driver->getImageURL();
?>
<? if (!empty($isShownAt) || !empty($imageURL)): ?>
  <div id="is-shown">
    <? if (!empty($isShownAt)): ?>
      <p>
        <?= $this->transEsc('isShownAt') ?><br/>
        <a href="http://hdl.handle.net/<?= $isShownAt ?>" target="_blank">
          http://hdl.handle.net/<?= $isShownAt ?>
        </a>
      </p>
    <? endif; ?>

    <? if (!empty($imageURL)): ?>
      <p>
        <?= $this->transEsc('isShownBy') ?><br/>
        <a href="<?= $imageURL ?>" target="_blank">
          <?= $imageURL ?>
        </a>
      </p>
    <? endif; ?>
  </div>
<? endif; ?>

<?
$copyrightA = $this->driver->getCopyrightA();
$isShownBy = $this->driver->getIsShownBy();
?>
<? if (!empty($copyrightA) || ($copyrightA != 'Public Domain.') && !empty($isShownBy)): ?>
  <div id="copyright">
    <h4><?=$this->transEsc('copyright.use')?></h4>

    <p>
      <a href="<?=$this->translate('copyright.consult.href')?>" target="_blank">
        <?=$this->transEsc('copyright.consult')?>
      </a>
    </p>

    <? $copyrightB = $this->driver->getCopyrightB(); if (empty($copyrightB)): ?>
      <p><?=$this->transEsc('copyright.unknown')?></p>
    <? else: ?>
      <p><?=$this->transEsc('copyright.known')?></p>
    <? endif; ?>
  </div>
<? endif; ?>

<?=$this->record($this->driver)->getPreviews()?>

