<h2><?=$this->transEsc('About')?></h2>

<? if ($this->layout()->userLang === 'nl'): ?>
    <p>
        <b>search.socialhistory.org</b> is de catalogus van het <a href="http://socialhistory.org/">Internationaal
            Instituut voor Sociale Geschiedenis (IISG)</a>,
        het <a href="http://www.neha.nl/">Nederlands Economisch Historisch Archief (NEHA)</a> en <a
            href="http://www.persmuseum.nl/">Permsuseum</a>.<br/>
        Voor praktische informatie en antwoorden op veel gestelde vragen met betrekking tot het raadplegen van deze
        collecties zie <a href="http://socialhistory.org/nl/dienstverlening">Dienstverlening</a><br/>
        De taalwissel heeft betrekking op de weergave van de labels in de interface. De taal van de data zelf
        wijzigt niet.
    </p>

    <h3>Nadere toelichting</h3>

    <p>
        <b>
            <a href="<?= $this->url('search-results') . '?' . http_build_query(array('type' => 'AllFields', 'filter[]' => 'format:"Archives"')); ?>">Archieven</a></b>
        – beschrijvingen en
        inventarissen van alle archiefcollecties van het IISG en Persmuseum. <br/>
        Voor bijzondere collecties van het NEHA zie: <a href="http://www.neha.nl/specialcollections/a.php">www.neha.nl/specialcollections</a>.<br/>
        De Nederlandse archieven zijn voorzien van een korte beschrijving in het Nederlands, de buitenlandse
        archieven hebben alleen een korte beschrijving in het Engels.<br/>
        Van ruim 1200 archieven is eveneens een inventaris beschikbaar. De taal van de inventaris hangt af van het
        land van herkomst van het archief en kan Nederlands, Engels, Duits, Frans of
        Spaans zijn.<br/>
        Meer informatie over de archieven: <a href="http://socialhistory.org/nl/archieven">socialhistory.org/nl/archieven</a>.
    </p>

    <p>
        <b><a href="<?= $this->url('search-results') . '?' . http_build_query(array('type' => 'AllFields', 'filter[]' => 'format:"Documentation"')); ?>">Documentatie</a></b>
        – pamfletten,
        flyers en kleine brochures uit de collectie van het IISG geordend op land / rubriek.<br/>
        Een introductie tot deze collectie is te vinden op: <a
            href="http://socialhistory.org/nl/collecties/documentatie">socialhistory.org/nl/collecties/documentatie</a>.
    </p>

    <p>
        <b><a href="<?= $this->url('search-results') . '?' . http_build_query(array('type' => 'AllFields', 'filter[]' => 'format:"Books and brochures"')); ?>">Boeken
                en brochures</a></b> – gegevens
        van alle boeken en brochures in de bibliotheek van het IISG, NEHA en Persmuseum.</p>

    <p>
        <b><a href="<?= $this->url('search-results') . '?' . http_build_query(array('type' => 'AllFields', 'filter[]' => 'format:"Serials"')); ?>">Periodieken</a></b>
        – 250.000 beschrijvingen
        van kranten, tijdschriften, jaarboeken en jaarverslagen in de bibliotheek van het IISG, NEHA en Persmuseum.
    </p>

    <p>
        <b><a href="<?= $this->url('search-results') . '?' . http_build_query(array('type' => 'AllFields', 'filter[]' => 'format:"Visual documents"')); ?>">Beeldmateriaal</a></b>
        – de beeldcollectie omvat
        onder meer zo'n 250.000 foto's, 138.000 negatieven en 22.000 tekeningen, de grootste collecties affiches
        (ca. 125.000) in Nederland en bewaart enkele honderden vaandels. Daarnaast omvat
        de collectie aanzienlijke hoeveelheden film (ca. 2500), video's (ca. 4000) en buttons. Van de beeldcollectie
        zijn meer dan 200.000 afbeeldingen digitaal beschikbaar.<br/>
        Een overzicht van de gebruikte trefwoorden vindt u in de <a
            href="http://socialhistory.org/sites/default/files/docs/thesaurus_image_and_sound_collections_0.doc">thesauruslijst</a><br/>
        Meer informatie: <a href="http://socialhistory.org/nl/collecties/beeld-geluid">socialhistory.org/nl/collecties/beeld-geluid</a>.
    </p>

    <p>
        <b><a href="<?= $this->url('search-results') . '?' . http_build_query(array('type' => 'AllFields', 'filter[]' => 'format:"Music and sound"')); ?>">Muziek
                en geluid</a></b> - gegevens van de collectie
        strijd- en protestliederen; historisch geluidsmateriaal, zowel documentair uitgegeven als originele opnames.
        Onder andere redevoeringen voorlieden, congressen en bijeenkomsten,
        programma's rond voorlieden en gebeurtenissen, interview- en oral history projecten rond onderzoeken en
        publicaties. <br/>
        Meer informatie: <a
            href="http://socialhistory.org/nl/collecties/geluid">socialhistory.org/nl/collecties/geluid</a>.
    </p>
<? else: ?>
    <p>
        <b>search.socialhistory.org</b> is a search platform for the collections of the <a
            href="http://socialhistory.org/en">International Institute of Social History
            (IISH)</a>, <a href="http://www.neha.nl/">Netherlands Economic History Archive</a> (NEHA), and <a
            href="http://www.persmuseum.nl/">Persmuseum</a>.<br/>
        For practical information and answers to FAQs on accessing the collections please see <a
            href="http://socialhistory.org/en/services">Services</a>.<br/>
        The language switch applies to the labels on the website. The language of the data itself does not change.
    </p>

    <h3>Additional information</h3>

    <p>
        <b><a href="<?= $this->url('search-results') . '?' . http_build_query(array('type' => 'AllFields', 'filter[]' => 'format:"Archives"')); ?>">Archives</a></b>
        – descriptions and inventories to
        archival collections of IISH and Persmuseum.<br/>
        For NEHA special collections see the <a href="http://www.neha.nl/specialcollections/a.php">NEHA
            website</a>.<br/>
        For Dutch archives a short description in Dutch is available, for all other archives the short description
        is in English. A search aid is available for over 1200 archives and can be in
        Dutch, English, German, French or Spanish, depending on the archives country of origin.<br/>
        More information: <a href="http://socialhistory.org/en/archives">socialhistory.org/en/archives</a>.</p>

    <p>
        <b><a href="<?= $this->url('search-results') . '?' . http_build_query(array('type' => 'AllFields', 'filter[]' => 'format:"Documentation"')); ?>">Documentation</a></b>
        – pamphlets, leaflets, small
        brochures from IISH collections arranged according to country / category.<br/>
        An introduction to this collection is available at <a
            href="http://socialhistory.org/en/collections/documentation">socialhistory.org/en/collections/documentation</a>.
    </p>

    <p>
        <b><a href="<?= $this->url('search-results') . '?' . http_build_query(array('type' => 'AllFields', 'filter[]' => 'format:"Books and brochures"')); ?>">Books
                and brochures</a></b> – contains records
        of all books and brochures in the library of IISH, NEHA, and Persmuseum.</p>

    <p>
        <b><a href="<?= $this->url('search-results') . '?' . http_build_query(array('type' => 'AllFields', 'filter[]' => 'format:"Serials"')); ?>">Serials</a></b>
        – contains 250,000 records of
        all newspapers, journal, yearbooks, and annual reports in the collections of IISH, NEHA, and, Persmuseum.
    </p>

    <p>
        <b><a href="<?= $this->url('search-results') . '?' . http_build_query(array('type' => 'AllFields', 'filter[]' => 'format:"Visual documents"')); ?>">Visual
                Documents</a></b> – the image collection
        held by the IISH includes about 250,000 photos, 138,000 negatives, and 22,000 drawings. The Institute has
        one of the largest collections of posters in the Netherlands (ca. 125,000)
        as well as several hundred banners. In addition, the collections include a considerable number of films (ca.
        2500), videos (ca. 4000), and buttons. Over 200,000 images are available digitally.<br/>
        There is a subject index in the <a
            href="http://socialhistory.org/sites/default/files/docs/thesaurus_image_and_sound_collections.doc">thesaurus</a>.<br/>
        More information: <a href="http://socialhistory.org/en/collections/image-sound">socialhistory.org/en/collections/image-sound</a>.
    </p>

    <p>
        <b><a href="<?= $this->url('search-results') . '?' . http_build_query(array('type' => 'AllFields', 'filter[]' => 'format:"Music and sound"')); ?>">Music
                and sound</a></b> - songs of struggle and protest;
        historical recordings, in original and published. Speeches party leaders, congresses and meetings,
        interviews and oral history projects.<br/>
        More information: <a
            href="http://socialhistory.org/en/collections/sound">socialhistory.org/en/collections/sound</a>.
    </p>
<? endif ?>