<div class="row" vocab="http://schema.org/" resource="#record" typeof="<?=$this->driver->getSchemaOrgFormats()?> Product">
  <div class="visible-print text-center">
    <? $langClass = ($this->layout()->userLang === 'nl') ? 'nl' : 'en'; ?>
    <img src="<?=$this->imageLink('IISG-logo-' . $langClass . '.jpg')?>"/>
  </div>

  <h3 property="name"><?=$this->escapeHtml($this->driver->getShortTitle())?></h3>

  <div class="col-sm-5 col-sm-push-7">
    <div class="text-center">
      <? /* Display thumbnail if appropriate: */ ?>
      <? $mediumThumb = $this->record($this->driver)->getThumbnail('medium'); $largeThumb = $this->record($this->driver)->getThumbnail('large'); ?>
      <? if ($mediumThumb): ?>
        <? if ($largeThumb): ?><a href="<?=$this->escapeHtmlAttr($largeThumb)?>"><? endif; ?>
          <img alt="<?=$this->transEsc('Cover Image')?>" class="recordcover" src="<?=$this->escapeHtmlAttr($mediumThumb);?>"/>
        <? if ($largeThumb): ?></a><? endif; ?>
      <? else: ?>
        <img src="<?=$this->url('cover-unavailable')?>" class="recordcover hidden-print" alt="<?=$this->transEsc('No Cover Image')?>"/>
      <? endif; ?>

      <? /* Display qrcode if appropriate: */ ?>
      <? $QRCode = $this->record($this->driver)->getQRCode("core"); ?>
      <? if($QRCode): ?>
        <span class="hidden-xs">
          <br/><img alt="<?=$this->transEsc('QR Code')?>" class="qrcode" src="<?=$this->escapeHtmlAttr($QRCode);?>"/>
        </span>
      <? endif; ?>
    </div>
  </div>

  <div class="col-sm-7 col-sm-pull-5">
    <? if ($this->userlist()->getMode() !== 'disabled'): ?>
      <? /* Display the lists that this record is saved to */ ?>
      <div class="savedLists hidden alert alert-info" id="savedLists">
        <strong><?=$this->transEsc("Saved in")?>:</strong>
      </div>
    <? endif; ?>

    <?/* Display Main Details */?>
    <table class="table table-striped" summary="<?=$this->transEsc('Bibliographic Details')?>">
      <? $journalTitle = $this->driver->getContainerTitle(); if (!empty($journalTitle)): ?>
      <tr>
        <th><?=$this->transEsc('Journal Title')?>:</th>
        <td>
          <a href="<?=$this->record($this->driver)->getLink('journaltitle', $journalTitle)?>"><?=$this->escapeHtml($journalTitle)?></a>
          <? $ref = $this->driver->getContainerReference(); if (!empty($ref)) { echo $this->escapeHtml($ref); } ?>
        </td>
      </tr>
      <? endif; ?>

      <? $nextTitles = $this->driver->getNewerTitles(); $prevTitles = $this->driver->getPreviousTitles(); ?>
      <? if (!empty($nextTitles)): ?>
      <tr>
        <th><?=$this->transEsc('New Title')?>: </th>
        <td>
          <? foreach($nextTitles as $field): ?>
            <a href="<?=$this->record($this->driver)->getLink('title', $field)?>"><?=$this->escapeHtml($field)?></a><br/>
          <? endforeach; ?>
        </td>
      </tr>
      <? endif; ?>

      <? if (!empty($prevTitles)): ?>
      <tr>
        <th><?=$this->transEsc('Previous Title')?>: </th>
        <td>
          <? foreach($prevTitles as $field): ?>
            <a href="<?=$this->record($this->driver)->getLink('title', $field)?>"><?=$this->escapeHtml($field)?></a><br/>
          <? endforeach; ?>
        </td>
      </tr>
      <? endif; ?>

      <? $authors = $this->driver->getDeduplicatedAuthors(); ?>
      <? if (isset($authors['main']) && !empty($authors['main'])): ?>
        <tr>
          <th><?=$this->transEsc('Main Author')?>: </th>
          <td property="author"><a href="<?=$this->record($this->driver)->getLink('author', $authors['main'])?>"><?=$this->escapeHtml($authors['main'])?></a></td>
        </tr>
      <? endif; ?>

      <? if (isset($authors['corporate']) && !empty($authors['corporate'])): ?>
        <tr>
          <th><?=$this->transEsc('Corporate Author')?>: </th>
          <td property="creator"><a href="<?=$this->record($this->driver)->getLink('author', $authors['corporate'])?>"><?=$this->escapeHtml($authors['corporate'])?></a></td>
        </tr>
      <? endif; ?>

      <? if (isset($authors['secondary']) && !empty($authors['secondary'])): ?>
        <tr>
          <th><?=$this->transEsc('Other Authors')?>: </th>
          <td>
            <? $i = 0; foreach ($authors['secondary'] as $field): ?><?=($i++ == 0)?'':', '?><span property="contributor"><a href="<?=$this->record($this->driver)->getLink('author', $field)?>"><?=$this->escapeHtml($field)?></a></span><? endforeach; ?>
          </td>
        </tr>
      <? endif; ?>

      <? $formats = $this->driver->getFormats(); if (!empty($formats)): ?>
        <tr>
          <th>&nbsp;</th>
          <td><?=$this->record($this->driver)->getFormatList()?></td>
        </tr>
      <? endif; ?>

      <? $publications = $this->driver->getPublicationDetails(); if (!empty($publications)): ?>
      <tr>
        <th><?=$this->transEsc('Published')?>: </th>
        <td>
          <? foreach ($publications as $field): ?>
            <span property="publisher" typeof="Organization">
            <? $pubPlace = $field->getPlace(); if (!empty($pubPlace)): ?>
              <span property="location"><?=$this->escapeHtml($pubPlace)?></span>
            <? endif; ?>
            <? $pubName = $field->getName(); if (!empty($pubName)): ?>
              <span property="name"><?=$this->escapeHtml($pubName)?></span>
            <? endif; ?>
            </span>
            <? $pubDate = $field->getDate(); if (!empty($pubDate)): ?>
              <span property="publicationDate"><?=$this->escapeHtml($pubDate)?></span>
            <? endif; ?>
            <? $extendedDateSpanPublisher = $this->driver->getExtendedDateSpanPublisher(); if (!empty($extendedDateSpanPublisher)): ?>
              <span property="dateSpan"><?=$this->escapeHtml($extendedDateSpanPublisher)?></span>
            <? endif; ?>
            <br/>
          <? endforeach; ?>
        </td>
      </tr>
      <? endif; ?>

      <? $edition = $this->driver->getEdition(); if (!empty($edition)): ?>
      <tr>
        <th><?=$this->transEsc('Edition')?>: </th>
        <td property="bookEdition"><?=$this->escapeHtml($edition)?></td>
      </tr>
      <? endif; ?>

      <?/* Display series section if at least one series exists. */?>
      <? $series = $this->driver->getSeries(); if (!empty($series)): ?>
      <tr>
        <th><?=$this->transEsc('Series')?>: </th>
        <td>
          <? foreach ($series as $field): ?>
            <?/* Depending on the record driver, $field may either be an array with
               "name" and "number" keys or a flat string containing only the series
               name.  We should account for both cases to maximize compatibility. */?>
            <? if (is_array($field)): ?>
              <? if (!empty($field['name'])): ?>
                <a href="<?=$this->record($this->driver)->getLink('series', $field['name'])?>"><?=$this->escapeHtml($field['name'])?></a>
                <? if (!empty($field['number'])): ?>
                  <?=$this->escapeHtml($field['number'])?>
                <? endif; ?>
                <br/>
              <? endif; ?>
            <? else: ?>
              <a href="<?=$this->record($this->driver)->getLink('series', $field)?>"><?=$this->escapeHtml($field)?></a><br/>
            <? endif; ?>
          <? endforeach; ?>
        </td>
      </tr>
      <? endif; ?>

      <? $subjects = $this->driver->getAllSubjectHeadings(); if (!empty($subjects)): ?>
        <tr>
          <th><?=$this->transEsc('Subjects')?>: </th>
          <td>
            <? foreach ($subjects as $field): ?>
              <div class="subjectLine" property="keywords">
                <? $subject = ''; ?>
                <? if(count($field) == 1) $field = explode('--', $field[0]); ?>
                <? $i = 0; foreach ($field as $subfield): ?>
                  <?=($i++ == 0) ? '' : ' &gt; '?>
                  <? $subject = trim($subject . ' ' . $subfield); ?>
                  <a class="backlink" title="<?=$this->escapeHtmlAttr($subject)?>" href="<?=$this->record($this->driver)->getLink('subject', $subject)?>"><?=trim($this->escapeHtml($subfield))?></a>
                <? endforeach; ?>
              </div>
            <? endforeach; ?>
          </td>
        </tr>
      <? endif; ?>
    </table>
    <?/* End Main Details */?>
  </div>
</div>